### ISSUE TITLE
Add option to use absolute positioning

### ISSUE THREAD

**Issue by wbattel4607** [tongyy/react-native-draggable#10]
The only problem I'm having with this library is using offsets instead of absolute positioning.

Is there a way we could add top/left/bottom/right properties like CSS absolute positioning that could be used instead of the offsets? Like `top={43} left={width/8-18}` instead of `offsetX={-50} offsetY={-100}`

The dev could choose to use one or the other.

**Comment by tongyy** [comment]
@wbattel4607 I added x,y,z for you in the latest patch.

**Comment by wbattel4607** [comment]
@tongyy awesome! Thank you!
