### ISSUE TITLE
Add a way to manually reset Draggable to start position

### ISSUE THREAD

**Issue by wbattel4607** [tongyy/react-native-draggable#11]
My users need to be able to drag the object around (including releasing it and then dragging again where they left off) and then reset it to its starting position when they press a button.

Can we add a function to reset the Draggable object to its initial offset? It could be done something like the refs used in r[eact-native-modal-box](https://github.com/maxs15/react-native-modalbox)

i.e., like this

```
someFunction() {
    this.refs.exampleModal.open();
}

someOtherFunction() {
    this.refs.exampleModal.close();
}

render() {
    <Modal style={styles.modal} ref={"exampleModal"}>
        ...
    </Modal>
}
```

**Comment by tongyy** [comment]
I published this patch.
react-native-draggable@1.0.9
