### ISSUE TITLE
Not working with React Native V0.66.0

### ISSUE THREAD

**Issue by AdhamMahmoud98** [tongyy/react-native-draggable#116]
I updated my project's react native version from 0.63.4 to 0.66.0. the dragging and functions such as (onPressIn, onLongPress) isn't working or responding at all

**Comment by AdhamMahmoud98** [comment]
I did some investigation. Remove the Touchable Opacity in draggable.js and move the draggable content inside the Animated.view. The container styles will be messed up but the dragging will be work.

**Comment by ghost** [comment]
I found that the problem is with the `Animated.View`'s positioning. If you add a css property to give it 100% height, then everything will work.

**Comment by AdhamMahmoud98** [comment]
@jp-qbic Your solution works thanks a lot !
