### ISSUE TITLE
Is it possible to just have it pop back to its original location after dragging

### ISSUE THREAD

**Issue by professorx00** [tongyy/react-native-draggable#118]
Is it possible to just have it pop back to its original location after dragging? I have a draggable on top of a map and this is slowing down the spring back animation. I am not seeing a clear way of just setting it back to origins on release?

**Comment by kej-jay** [comment]
Are you looking for the _shouldReverse_ property?

**Comment by professorx00** [comment]
I was able to fix it. Thanks for reaponding
