### ISSUE TITLE
Recognize drop on a certain field

### ISSUE THREAD

**Issue by Sir-hennihau** [tongyy/react-native-draggable#14]
Hi!
Is there a out of the box solution for a component to register, **if it was dropped onto a certain view**?
For example a certain function should be fired then.

Thanks in advance and have a nice day.

**Comment by tongyy** [comment]
Draggable has properties x,y , maybe you can detect them and move to your view or position.

**Comment by Razzwan** [comment]
I tried do like you say, but can not understand, how I can "detect x and y" hmm. Will figure out

**Comment by Razzwan** [comment]
Maybe, you can help me?

**Comment by wolfrobert35** [comment]
You can access the drop coordinates by: t
`his.myComponent.state.pan.x
his.myComponent.state.pan.y`

This article might be helpful:
https://blog.reactnativecoach.com/creating-draggable-component-with-react-native-132d30c27cb0
