### ISSUE TITLE
Draggable element hide behind view [Android only]

### ISSUE THREAD

**Issue by venillas** [tongyy/react-native-draggable#15]
Hello, 

When I try to drag an element with your example code, that element is dragged behind the view.

`return (
    <View >
        <Draggable renderSize={56} renderColor='black' offsetX={-100} offsetY={-200} renderText='A' pressDrag={()=>alert('touched!!')}/> 
        <Draggable reverse={false} renderColor='red' renderShape='square' offsetX={0} offsetY={0} renderText='B'/>
        <Draggable/>
    </View>
);` 

Thanks in advance for your answer
![screenshot_20180122-111943](https://user-images.githubusercontent.com/23377597/35216115-ccd2ec24-ff66-11e7-9783-44faa20aa0c6.jpg)

**Comment by tongyy** [comment]
Does it have any error on your console?  you can set "z" of Draggable and assure that must be over.

**Comment by venillas** [comment]
There is no error, and even with the "z" it has the same behavior 

` <Draggable z={100} renderSize={56} renderColor='black' offsetX={-100} offsetY={-200} renderText='A' pressDrag={()=>alert('touched!!')}/> `

**Comment by tongyy** [comment]
Provide your run-time environment plz. I run at IOS 10-11 and Android-23 without problems.

**Comment by venillas** [comment]
Runtime env : Android 7.1.1

**Comment by venillas** [comment]
Please check this [link](https://drive.google.com/file/d/1aeE0gD0Hr6-J06m-QEd6uEWRLqgvHnae/view?usp=sharing)

**Comment by tongyy** [comment]
@venillas  Thank you for your detailed information.
I fixed it and published with 1.0.12 version.

**Comment by venillas** [comment]
Thank you !
