### ISSUE TITLE
draggable does not work properly with imageSource

### ISSUE THREAD

**Issue by maniks04** [tongyy/react-native-draggable#16]
works fine with shapes.. but once I include an imageSource for some png, it gives me a warning for a failed prop.type

Warning: failed prop type: invalid prop 'imageSource' of type 'object' supplied to 'Draggable', expected 'number'.

<Draggable reverse={false} renderShape='image' imageSource={this.state.source} renderSize={70} offsetX={50} offsetY={50}/>

The image shows up, so works fine, but the error keeps showing up!

**Comment by tongyy** [comment]
Hi,
The image needs to support two types check, one is number by using require("sources.png") the other is object by downloading URI.
I fixed and publish it to version 1.0.13. Thanks for providing the bug-issue.
