### ISSUE TITLE
Draggable being moved along with scrollview

### ISSUE THREAD

**Issue by ZChenzy** [tongyy/react-native-draggable#21]
Not sure if this is a bug but my draggable moves along with sibling scrollview or even nephew scrollview.

**Comment by tongyy** [comment]
draggable should be fixed on the top view. does your view has a complex layout? could you provide the simplest code which reproduces it?

**Comment by ZChenzy** [comment]
Hmm, I could not produce it in vanilla react-native. I had it in a <Content> tag (from native base) next to a ScrollView which was causing me issues(in theory it shouldn't?). Probably a native-base thing. It is fine when you move it out. Probably could close for now

`import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { ScrollView } from 'react-native-gesture-handler';
import Draggable from 'react-native-draggable';
import {Content} from 'native-base'
export default class App extends React.Component {
	render() {
		let arr = [];
		for (let i = 0; i < 100; i++) arr.push(<Text>ROW OF TEXT ASD ASD ASD ASD SAD ASD ASD ASDSA</Text>);
		return (
			<View style={styles.container}>
			<Content>
				<ScrollView>{arr}</ScrollView>
				<Draggable />
				</Content>
			</View>
		);
	}
}

const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: '#fff',
		alignItems: 'center',
		justifyContent: 'center'
	}
});
`

**Comment by tongyy** [comment]
could you try the following code? Draggalbe should be under the top view as the same layer as your content
```
<Content>
  <ScrollView>{arr}</ScrollView>
  //<Draggable />
</Content>
<Draggable />
```

**Comment by alikh31** [comment]
I would suggest using pressInDrag and PressOutDrag to enable and disable scroll view, something like:

``` javascript
...

<ScrollView scrollEnabled={this.state.scrollEnabled}>

   ...

  <Draggable
      pressInDrag={() => setState({ scrollEnabled: false })}
      pressOutDrag={() => setState({ scrollEnabled: true })}
   />
</ScrollView>
```
