### ISSUE TITLE
How to maintain the position of each draggable in the state

### ISSUE THREAD

**Issue by ManalLiaquat** [tongyy/react-native-draggable#27]
When I reload the app state,  draggable reset the positions. How can I maintain the position of each draggale (I have many draggables)

**Comment by tongyy** [comment]
There are a lot of libs which allow you to persist data.
https://github.com/jasonmerino/react-native-simple-store
https://github.com/react-native-community/async-storage

**Comment by ManalLiaquat** [comment]
I have an array of objects, and I am rendering them with with x, y values and getting the updated values from the library function getPosition() but when I update the object with the updated x and y, draggable move the image twice, without updating it works fine but I have to update the array for each image. When I reOpen my app so each image will be there with their x and y values (coordinates).

**Comment by tongyy** [comment]
It seems you have persisted data but you do not check the x, y after reloading. Can you make sure the persistent data is correct?

**Comment by ManalLiaquat** [comment]
When I run this code, draggable image moves twice. For example, the initial `x=1` and `y=1`, the draggable image shown at the top-left corner of the screen, and I move the image to `x=20` and `y=35` so the image move with same `x=20` and `y=35`, where I release the draggable image it move twice i.e. `x=40` and `y=70`. This is happening on `setState` without `setState` it works fine.
```
<Draggable {...imageProp_here} x={this.state.x} y={this.state.y} ref={ref=>this.myDrag=ref} onPressDragRelesae={()=>{
  const { x, y } =this.myDrag.getPosition();
  this.setState({x,y});
  }}  />
```

**Comment by tongyy** [comment]
you pass x, y by props (x={this.state.x} y={this.state.y}).  x and y are your initial positions. since you setState({x, y}) and x, y are passed into Draggable as props to change initial positions and be doubled it from Draggable's setState and your setState of the callback function.

Here's an idea might help you.
<Draggable {...imageProp_here} **x={getPersistDataX or defaultX} y={getPersistDataY or defaultY}** ref={ref=>this.myDrag=ref} onPressDragRelesae={()=>{
  const { x, y } =this.myDrag.getPosition();
  **persistData({x,y});**
  //this.setState({x,y});
  }}  />

**Comment by ManalLiaquat** [comment]
Thanks @tongyy for your time

**Comment by owenpriestley** [comment]
@ManalLiaquat Please can you post more of the code you used for this issue? I think I'm experiencing the same problem

**Comment by ManalLiaquat** [comment]
> @ManalLiaquat Please can you post more of the code you used for this issue? I think I'm experiencing the same problem

Sorry for the late reply! but the solution is described by @tongyy [in the above comment](https://github.com/tongyy/react-native-draggable/issues/27#issuecomment-533840877)

**Comment by Ehtesham25** [comment]
@ManalLiaquat  I want to drag the icon from Initial position to right. it works fine but it drags to top and bottom i want to drag icon only to right Direction. How I presist it to not drag to other directions. Check my code. Thank you.

<Draggable
            onDrag={onDrag}
            shouldReverse={true}
            x={pacmanCurrentPosition}
            y={0}
            minX={0}
            maxX={280}
            minY={0}
            maxY={0}
            onPressIn={onPressIn}
            onPressOut={onPressOut}
            onReverse={() => {
        
              return {x: 0, y: 0};
            }}
            onShortPressRelease={onShortPressRelease}
            onDragRelease={onDragRelease}>
            <Icon
              type="header-bite"
              heigh={wp(8)}
              width={wp(5.5)}
              marg={`${wp(2.5)}px 0 0 ${wp(2)}px`}
            />
          </Draggable>
