### ISSUE TITLE
Can Convert moveX & moveY as Percentage ? because if i need to display an item to another mobile it very different 

### ISSUE THREAD

**Issue by HusseinElGanzory** [tongyy/react-native-draggable#29]

**Comment by tongyy** [comment]
you can calculate percentages by Window.height and width for the workaround

**Comment by HusseinElGanzory** [comment]
> you can calculate percentages by Window.height and width for the workaround

can you give me an example about it if applicable

**Comment by tongyy** [comment]
that's my idea
DB: width:20%, height: 30%
x = Window.width * 20% 
y = Window.height * 30%
--------------------------------
x = 30, y = 50
db.save(30/Window.width, 50/Window.height);

**Comment by HusseinElGanzory** [comment]
> x = Window.width * 20%
> y = Window.height * 30%
> //save percentages
> x = 30, y = 50
> db.save(30/Window.width, 50/Window.height);



> that's my idea
> //convert percentages
> DB: width:20%, height: 30%
> x = Window.width * 20%
> y = Window.height * 30%
> //save percentages
> x = 30, y = 50
> db.save(30/Window.width, 50/Window.height);

an try to do that
