### ISSUE TITLE
ref is null

### ISSUE THREAD

**Issue by dyarfaradj** [tongyy/react-native-draggable#33]
Can't get ref for the component, it's null all the time. 
Version: "react-native-draggable": "^2.0.0"

**Comment by tongyy** [comment]
@baconcheese113 any idea for this? is a limit of functional component? I forgot we have two methods which are reversePosition and getPosition.

**Comment by baconcheese113** [comment]
@dyarfaradj @tongyy Yea, was trying to think of ways to handle that. If you need to maintain the location of the `Draggable` you can set a `React.useRef()` variable from the `onMove` callback

```
const locationRef = React.useRef();
...
const handleOnMove = event => {
  const { locationX: x, locationY: y } = event.nativeEvent;
  locationRef.current = { x, y };
}
<Draggable onMove={handleOnMove} />
```

**Comment by tongyy** [comment]
Hey guys I updated READE.ME. getPosition can be replaced by passing pressDragRelease callback instead. I think if we want to use functional component, methods of react-native-draggable are no longer available. because It's kind of antipattern.
