### ISSUE TITLE
Question: Turning off initial Drag-Start-Animation

### ISSUE THREAD

**Issue by sofarsoghood** [tongyy/react-native-draggable#38]
Hi there!

Pretty cool stuff you did there!
I'm using it for modal-resizing and got one question:
When starting to resize the modal (which is done via your draggable) there is an animation which lights up the `<Draggable>` for a short period. Is it possible to turn that animation off?

Greets
sofar

**Comment by baconcheese113** [comment]
I think you're referring to the [ActiveOpacity](https://facebook.github.io/react-native/docs/touchableopacity#activeopacity)?

If so, we now expose `touchableOpacityProps` and `animatedViewProps` for passing through component-specific props.

You'll want to do something like this:
`
<Draggable touchableOpacityProps={{activeOpacity: 1}}>
  ...
</Draggable>
`

**Comment by sofarsoghood** [comment]
Works, thanks a lot!
Just another small thing i came across: the Readme says the default value for `debug` would be `true`, but in the `Draggable.defaultProps` the value is set to `false` as far as i can see :)

**Comment by baconcheese113** [comment]
Oh good catch! That should definitely be false by default. I've gone ahead and updated it.

**Comment by sofarsoghood** [comment]
That was fast :D
