### ISSUE TITLE
error when run app

### ISSUE THREAD

**Issue by TranHanHieu** [tongyy/react-native-draggable#4]
node_modules/react-native-draggable/node_modules/react-native/package.json
node_modules/react-native/package.json

I need help, please!

**Comment by tongyy** [comment]
@TranHanHieu I need more a detailed error message. Is your issue the same as #1 ?

**Comment by TranHanHieu** [comment]
Yes, Can you help me.

**Comment by tongyy** [comment]
@TranHanHieu I pushed the Vesrion 1.0.7 of react-native-draggable. 
Fix your react-native-draggable version in your package.json, and try it again.
