### ISSUE TITLE
Not working in Android at all.

### ISSUE THREAD

**Issue by Dhruv56** [tongyy/react-native-draggable#42]
I created a sample app by using the same examples as README. It worked on iOS but not on Android. Nothing is getting rendered on-screen in Android. Here is a screenshot.

![image](https://user-images.githubusercontent.com/14262321/75650804-0e5f1080-5c7d-11ea-8f50-f17bb6a4f846.png)

Android OS - 9.0 Pie, API 28

There is no error in the console also to debug it.

**Comment by baconcheese113** [comment]
@Dhruv56 Are you still experiencing this?

**Comment by android0code** [comment]
Same issue
