### ISSUE TITLE
Invalid props.style key `z` supplied to `View`

### ISSUE THREAD

**Issue by maki3000** [tongyy/react-native-draggable#46]
I'm getting this warning:
`Invalid props.style key 'z' supplied to 'View'`

Do I do something wrong? Shouldn't that be "zIndex" instead of just z?

Here some more of the warning:
```
Bad object: {
  "transitionProperty": "opacity",
  "transitionDuration": "0.15s",
  "userSelect": "none",
  "cursor": "pointer",
  "touchAction": "manipulation",
  "top": 37,
  "left": 306,
  "elevation": 1,
  "z": 1,
  "alignSelf": "baseline"
}
```
This "z": 1 most probably throws it.

**Comment by baconcheese113** [comment]
Unable to reproduce this, but it should definitely be `zIndex` for iOS
