### ISSUE TITLE
Avoid going out of the screen

### ISSUE THREAD

**Issue by jayan2019** [tongyy/react-native-draggable#48]
Now it allows moving the dragging component to go out of the mobile screen. Therefore is there any way to avoid draggable item going out of a component?

Or is there any way to limit the dragging component size?

I am using ```"react-native-draggable": "^3.0.0",```

**Comment by jayan2019** [comment]
it could be able to resolve by defining the x, y values from the container's layout props

Eg: ```minX={10} minY={10} maxX={layout.width - 10} maxY={layout.height - 10}```

**Comment by brianpaul-99** [comment]
ergr
 gat -- at  
 ewt
