### ISSUE TITLE
Draggable within parent boundaries

### ISSUE THREAD

**Issue by jenskuhrjorgensen** [tongyy/react-native-draggable#5]
Hi @tongyy 
I was wondering if you have any suggestions on how to make a draggable view which can only be dragged within certain boundaries, e.g. its parent? 
I'm facing a task where I want to place a marker on a background image and get the coordinates of the marker within the image. 

Best regards
Jens

**Comment by tongyy** [comment]
@jenskuhrjorgensen You can control what position can be move  on "onPanResponderMove" function of PanResponder.

**Comment by jenskuhrjorgensen** [comment]
Thx for the help and the snappy response 😀

**Comment by ImHamzaAnwer** [comment]
is there any example code for it ?
