### ISSUE TITLE
useNativeDriver was not specified

### ISSUE THREAD

**Issue by moficodes** [tongyy/react-native-draggable#50]
on android
react-native: 0.62.2
react-native-draggable: "^3.0.0"

I get a warning , 
```
Animated: 'useNativeDriver' was not specified. This is a required option and must be explicitly set to 'true' or 'false'
```

[This article](https://reactnative.dev/blog/2017/02/14/using-native-driver-for-animated.html) seems to be talking about it. But I am not sure how to fix this in this.

**Comment by baconcheese113** [comment]
React Native switched over to requiring `useNativeDriver` be set in .62.
https://reactnative.dev/blog/#deprecations

Should be a 1 line fix here:
https://github.com/tongyy/react-native-draggable/blob/master/Draggable.js#L253

@tongyy I'll go ahead and make this change and try pushing the new version to npm
