### ISSUE TITLE
Draggable children goes bellow others in IOS

### ISSUE THREAD

**Issue by Manfrin92** [tongyy/react-native-draggable#68]
Hello,

I made a simple draggable item that should execute a function when dragged to a certain point. That point is marked with an Icon and a text describing the action. E.g, accept. In Android when that draggable item reaches that icon and text it covers them as I expected. But in IOS that doesn't happen. The draggable item stays behind them. I tried to change the z property, but the problem was not solved. Actually I don't know how to set it.

Thanks.

**Comment by baconcheese113** [comment]
Z index in react-native doesn't work as expected (coming from web). You should always rely on **hierarchal rendering position** to ensure the layers are working how you'd like. If you're unable to re-order components in your current hierarchy you'll probably need to use portals to send the draggable to where you need it. I explained it a bit more here https://github.com/tongyy/react-native-draggable/pull/34#issue-347174658

**If you need portals....**
I'd recommend @cala/react-portal I've used this package to portal loading spinners in my own RN project here 
https://github.com/baconcheese113/chat2getherRN/blob/master/src/components/VideoGrid.js#L143
https://github.com/baconcheese113/chat2getherRN/blob/master/src/Screens/ChatHub.js#L107
