### ISSUE TITLE
How to disable onTouch blinks?

### ISSUE THREAD

**Issue by WeTruck** [tongyy/react-native-draggable#79]
Hi,

Thanks for the library.

How can I disable this onTouch opacity changing system?

![ezgif-4-dd54de67de29](https://user-images.githubusercontent.com/46923165/93668863-5d518380-fab1-11ea-9f60-67e5a645da1a.gif)

Here is my code,

```
import React, {Component} from 'react';
import {View} from 'react-native';
import Draggable from 'react-native-draggable';

export default class App extends Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <View>
        <Draggable
          x={200}
          y={300}
          renderSize={100}
          renderColor="red"
          renderText="B"
        />
      </View>
    );
  }
}
```

Thanks.

**Comment by kevinvayro** [comment]
Pass an object to the touchableOpacityProps prop of Draggable with activeOpacity set to 1. That should take care of it.

**Comment by WeTruck** [comment]
Thanks @kevinvayro , it worked :)
