### ISSUE TITLE
Center position isn't working

### ISSUE THREAD

**Issue by WeTruck** [tongyy/react-native-draggable#80]
Hi,

Thanks for the library.

Center position from parent element isn't working. This is my code:

```
import React, {Component} from 'react';
import {View, Text} from 'react-native';
import Draggable from 'react-native-draggable';

export default class App extends Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <View style={{alignItems: 'center'}}>
        <View>
          <Text>This is correctly centered</Text>
        </View>
        <View>
          <Draggable renderSize={100} renderColor="red" renderText="B" />
        </View>
      </View>
    );
  }
}
```

And this is the output:

![image](https://user-images.githubusercontent.com/46923165/93669938-297a5c00-fab9-11ea-9405-37ca8ac523b3.png)

Thanks.

**Comment by kevinvayro** [comment]
I believe this is acting as expected. 

The draggable component has a main view which is 100% screen width and this is the element which will react to your center align. 

The rendered child, the red square in this case, is positioned using the x and y props on load. You could set x equal to (screen width / 2) - (render size / 2).

**Comment by WeTruck** [comment]
Worked with your theory. Thanks 👍 :)
