### ISSUE TITLE
About a different implementation

### ISSUE THREAD

**Issue by btk** [tongyy/react-native-draggable#9]
Hey there, great work thank you so much.

Would you ever consider going through this kind of path for this project;

https://github.com/btk/react-native-draggable-holder

I feel like using children components might be more generic? I just want to learn your reason not to implement children components instead using a non-generic styling scheme?

Thank you.

**Comment by tongyy** [comment]
@btk Your idea is great. I also wanted to open child component spec, but I think it's complex for basic use.

The following code is my use of the project. I just tell Draggable what is my drag event function, then it works and fulfill all my requirements, so I don't need to know how to design child component, it's very easy to use.
`<Draggable pressDrag={dosomething}/>`

**Comment by Liampronan** [comment]
@btk 👍 to your implementation
